export * from "./auth/auth.store";
export * from "./operadores/operadores.store";
export * from "./proyectos/proyectos.store";
export * from "./adminoperadores/adminoperadores.store";
export * from "./clientes/clientes.store";
export * from "./labores/labores.store";
export * from "./siembra/siembra.store";
export * from "./riego/riego.store";
export * from "./plagas/plagas.store";
export * from "./equipo/equipo.store";
export * from "./usuariosresponsables/usuariores.store";
export * from "./perifericos/periferico.store";
export * from "./software/software.store";
export * from "./hardware/hardware.store";
export * from "./configuracionred/configred.store";
export * from "./usuariosistema/usuariosis.store";
export * from "./accesoremoto/accesoremoto.store";
export * from "./reportes/reporte.store";
export * from "./secretaria/secretaria.store";
export * from "./dependencias/dependencia.store";

// Note: Do not edit this file directly. Edit the files in the 'store' directory.
